#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) this run: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# This wizard must be run from the repo root (it reads/writes .env,
# .env.local, and supabase/config.toml relative to the current directory).
if [[ ! -f "supabase/config.toml" ]]; then
  printf 'Run this from the project root (chabod-catalogue), not from scripts/.\n' >&2
  exit 1
fi

banner "Chabod Choir Catalogue — hosted infra setup"

# ── Stage 1: Telegram bot ──────────────────────────────────────────────────
stage "Telegram bot"
say "We'll create the bot that delivers login codes and captures phone-number links."
open_url "https://t.me/botfather"
step "In Telegram, message BotFather: send /newbot"
step "Give it a display name, e.g. 'Chabod Choir Catalogue'."
step "Give it a username ending in 'bot', e.g. ChabodCatalogueBot."
step "BotFather replies with a token that looks like 123456789:AA...— copy it."
ENV_FILE=".env.local"
ask TELEGRAM_BOT_USERNAME "Bot username (without the @):"
write_env TELEGRAM_BOT_USERNAME "$TELEGRAM_BOT_USERNAME"

ENV_FILE=".env"
ask_secret TELEGRAM_BOT_TOKEN "Bot token:"
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"

# ── Stage 2: Hosted Supabase project ───────────────────────────────────────
stage "Hosted Supabase project"
say "We'll create the real Postgres/Auth/Storage project this app will run against."
open_url "https://supabase.com/dashboard/projects"
step "Click 'New project'. Pick your organization, name it (e.g. chabod-catalogue),"
step "set a strong database password — SAVE IT, you need it in the next stage too —"
step "pick a region close to your choir, and create it. Wait ~2 min for provisioning."
ENV_FILE=".env"
ask SUPABASE_PROJECT_REF "Project ref (the random string in the project's dashboard URL):"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
# Not written to any file on purpose — only needed transiently to link the
# CLI in the next stage, and isn't worth persisting to disk.
ask_secret SUPABASE_DB_PASSWORD "The database password you just set:"
say ""
step "Now open Project Settings -> API on that project."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api"
step "Copy the Project URL, the 'anon public' key, and the 'service_role' key."

ENV_FILE=".env.local"
NEXT_PUBLIC_SUPABASE_URL="https://${SUPABASE_PROJECT_REF}.supabase.co"
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the anon public key:"
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the service_role key:"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── Stage 3: Link the Supabase CLI ─────────────────────────────────────────
stage "Link the Supabase CLI"
say "This connects your local supabase/ folder to the hosted project so the"
say "remaining stages can push schema, config, and functions automatically."
say "supabase login opens a browser to authorize the CLI."
npx --yes supabase login
if SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" npx --yes supabase link --project-ref "$SUPABASE_PROJECT_REF"; then
  say "Linked."
else
  warn "Link failed — re-run this script once you've resolved it (it's safe to re-run)."
  exit 1
fi

# ── Stage 4: Push the database schema ──────────────────────────────────────
stage "Push database schema"
say "Applying supabase/migrations to the hosted project (songs, metadata fields,"
say "allowed_users, telegram_links, RLS policies, auth hooks)."
if npx --yes supabase db push --linked; then
  say "Schema pushed."
else
  warn "supabase db push failed — see error above. Fix it, then re-run this script."
  exit 1
fi

# ── Stage 5: Push auth config (safely) ─────────────────────────────────────
stage "Push auth config"
say "Wiring the before_user_created and Send SMS hooks on the hosted project."
say "The Send SMS hook needs its own production secret and the hosted function's"
say "URL (not the local host.docker.internal one), so we override those just for"
say "the linked remote — local dev config in config.toml is untouched."

PROD_SEND_SMS_HOOK_SECRET="v1,whsec_$(openssl rand -base64 32)"
ENV_FILE=".env" write_env PROD_SEND_SMS_HOOK_SECRET "$PROD_SEND_SMS_HOOK_SECRET"

if ! grep -q "^\[remotes\.production\]" supabase/config.toml; then
  {
    printf '\n[remotes.production]\n'
    printf 'project_id = "%s"\n\n' "$SUPABASE_PROJECT_REF"
    printf '[remotes.production.auth.hook.send_sms]\n'
    printf 'enabled = true\n'
    printf 'uri = "https://%s.supabase.co/functions/v1/telegram-send-sms"\n' "$SUPABASE_PROJECT_REF"
    printf 'secrets = "env(PROD_SEND_SMS_HOOK_SECRET)"\n'
  } >> supabase/config.toml
  say "Added a [remotes.production] override to supabase/config.toml."
else
  note "supabase/config.toml already has a [remotes.production] block — leaving it as is."
fi

say "Temporarily removing the local-only test_otp block so it can never reach"
say "production, pushing config, then restoring it for local dev."
cp supabase/config.toml supabase/config.toml.bak
awk '
  /^\[auth\.sms\.test_otp\]/ { skip=1 }
  skip && /^\[/ && !/^\[auth\.sms\.test_otp\]/ { skip=0 }
  !skip { print }
' supabase/config.toml.bak > supabase/config.toml

if npx --yes supabase config push --project-ref "$SUPABASE_PROJECT_REF"; then
  say "Auth config pushed."
else
  warn "config push failed — see error above."
fi
cp supabase/config.toml.bak supabase/config.toml
rm -f supabase/config.toml.bak

# ── Stage 6: Deploy edge functions + their secrets ─────────────────────────
stage "Deploy edge functions"
say "Deploying telegram-send-sms and telegram-webhook, and setting the runtime"
say "secrets they read at request time."

PROD_TELEGRAM_WEBHOOK_SECRET=$(openssl rand -base64 32)
ENV_FILE=".env" write_env PROD_TELEGRAM_WEBHOOK_SECRET "$PROD_TELEGRAM_WEBHOOK_SECRET"

if npx --yes supabase functions deploy --project-ref "$SUPABASE_PROJECT_REF" --no-verify-jwt; then
  say "Functions deployed."
else
  warn "functions deploy failed — see error above. Fix it, then re-run this script."
  exit 1
fi

if npx --yes supabase secrets set --project-ref "$SUPABASE_PROJECT_REF" \
  "telegram_bot_token=${TELEGRAM_BOT_TOKEN}" \
  "send_sms_hook_secret=${PROD_SEND_SMS_HOOK_SECRET}" \
  "telegram_webhook_secret=${PROD_TELEGRAM_WEBHOOK_SECRET}"; then
  say "Function secrets set."
else
  warn "supabase secrets set failed — see error above."
fi

# ── Stage 7: Register the Telegram webhook ─────────────────────────────────
stage "Register Telegram webhook"
say "Telling Telegram to send bot updates to the deployed telegram-webhook function."

WEBHOOK_URL="https://${SUPABASE_PROJECT_REF}.supabase.co/functions/v1/telegram-webhook"
RESP=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/setWebhook" \
  -d "url=${WEBHOOK_URL}" \
  -d "secret_token=${PROD_TELEGRAM_WEBHOOK_SECRET}")
printf '  %s\n' "$RESP"
if printf '%s' "$RESP" | grep -q '"ok":true'; then
  say "Webhook registered."
else
  warn "Telegram didn't confirm the webhook — check the response above."
fi

# ── Stage 8: Add yourself as the first admin ───────────────────────────────
stage "Add the first admin"
say "This inserts a row into allowed_users so you can actually log in once the"
say "app is deployed. You'll link this number to the bot on first login, same"
say "as the local dev flow."
ask ADMIN_PHONE_NUMBER "Your phone number, E.164 format (e.g. +15555550123):"
ask ADMIN_DISPLAY_NAME "Your display name (optional, Enter to skip):"

if [[ -n "$ADMIN_DISPLAY_NAME" ]]; then
  ADMIN_JSON=$(printf '{"phone_number":"%s","role":"admin","display_name":"%s"}' "$ADMIN_PHONE_NUMBER" "$ADMIN_DISPLAY_NAME")
else
  ADMIN_JSON=$(printf '{"phone_number":"%s","role":"admin","display_name":null}' "$ADMIN_PHONE_NUMBER")
fi

RESP=$(curl -s -X POST "https://${SUPABASE_PROJECT_REF}.supabase.co/rest/v1/allowed_users" \
  -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
  -H "Content-Type: application/json" \
  -H "Prefer: return=representation" \
  -d "$ADMIN_JSON")
printf '  %s\n' "$RESP"
if printf '%s' "$RESP" | grep -q "$ADMIN_PHONE_NUMBER"; then
  say "Added as admin."
else
  warn "That didn't look like success — check the response above (it may already exist)."
fi

# ── Stage 9: Deploy to Vercel ───────────────────────────────────────────────
stage "Deploy to Vercel"
say "vercel link will ask a few questions about the project — answer them for"
say "this repo. Then we set the four production env vars and deploy."
vercel link

for pair in \
  "NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}" \
  "NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}" \
  "SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}" \
  "TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}"
do
  name="${pair%%=*}"
  value="${pair#*=}"
  if printf '%s' "$value" | vercel env add "$name" production --force >/dev/null 2>&1; then
    printf '  %s✓ set%s Vercel env var %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel env var $name (set it manually: vercel env add $name production)")
    warn "couldn't set Vercel env var $name — set it manually"
  fi
done

if confirm "Deploy to production now (vercel --prod)?"; then
  vercel --prod
else
  note "Skipped — run 'vercel --prod' yourself when ready."
fi

finish
say "Next: open your deployed URL, log in with the admin phone number you added,"
say "link it to the Telegram bot, and you're live."
